#!name=  VVebo 小火箭专用
#!desc=修复VVebo用户主页时间线显示和粉丝列表 @androidcn适配
#!author=suiyuran

[URL Rewrite]
# 将带有 __vvebo_redirect=1 的请求从 user_timeline 重写为 profile/statuses/tab，并添加 containerid 参数
^https?://api\.weibo\.cn/2/statuses/user_timeline(\?.*)__vvebo_redirect=1&__vvebo_containerid=([^&]+)(.*)$ https://api.weibo.cn/2/profile/statuses/tab$1containerid=$2 302

[Script]

fix-vvebo-user-timeline = type=http-request, pattern=^https:\/\/api\.weibo\.cn\/2\/remind\/unread_count\?, requires-body=true,script-path=https://raw.githubusercontent.com/MockyBang/stash/main/scripts/fix-vvebo-user-timeline.js

fix-vvebo-user-timeline2 = type=http-request, pattern=^https:\/\/api\.weibo\.cn\/2\/statuses\/user_timeline\?, requires-body=true,script-path=https://raw.githubusercontent.com/MockyBang/stash/main/scripts/fix-vvebo-user-timeline.js

fix-vvebo-user-timeline3 = type=http-response, pattern=^https:\/\/api\.weibo\.cn\/2\/profile\/statuses\/tab\?,requires-body=true, script-path=https://raw.githubusercontent.com/MockyBang/stash/main/scripts/fix-vvebo-user-timeline.js

fix-vvebo-user-timeline4 = type=http-request, pattern=^https:\/\/api\.weibo\.cn\/2\/users\/show\?,requires-body=true, script-path=https://raw.githubusercontent.com/MockyBang/stash/main/scripts/fix-vvebo-user-timeline.js

fix-vvebo-fans = type=http-response, pattern=^https:\/\/api\.weibo\.cn\/2\/cardlist\?,requires-body=true, script-path=https://raw.githubusercontent.com/MockyBang/stash/main/scripts/fix-vvebo-fans.js, requires-body=true



[MITM]
hostname = %INSERT% api.weibo.cn
